# Generated by Django 3.1 on 2020-10-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_genre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('manufaturer', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('key_benifits', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=64)),
                ('safety_info', models.CharField(max_length=100)),
                ('other_info', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('genres', models.ManyToManyField(to='netmedsapp.medicine_type')),
            ],
        ),
    ]
