# Generated by Django 3.1 on 2020-10-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmedsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
