# Generated by Django 3.1 on 2020-10-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmedsapp', '0002_auto_20201019_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='netmedsapp.medicine_type'),
        ),
    ]
