# Generated by Django 3.1 on 2020-10-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmedsapp', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='number_of_items',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
