# Generated by Django 3.1 on 2020-10-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netmedsapp', '0006_cart_number_of_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
