# Generated by Django 3.0.6 on 2020-10-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmedsapp', '0007_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='key_benifits',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='other_info',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='safety_info',
            field=models.CharField(max_length=1000),
        ),
    ]
